/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef MAINBOARD_ERYING_SRMJ4_GPIO_H
#define MAINBOARD_ERYING_SRMJ4_GPIO_H

#include <gpio.h>

/* From inteltool via intelp2m -platform adl -f cb -iiii; short macros from comments. */
static const struct pad_config gpio_table[] = {
	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_B ------- */

	PAD_CFG_NF(GPP_B0, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_B1, NONE, DEEP, NF1),

	PAD_NC(GPP_B2, NONE),

	PAD_NC(GPP_B3, NONE),

	PAD_NC(GPP_B4, NONE),

	PAD_NC(GPP_B5, NONE),

	PAD_NC(GPP_B6, NONE),

	PAD_NC(GPP_B7, NONE),

	PAD_NC(GPP_B8, NONE),

	PAD_NC(GPP_B9, NONE),

	PAD_NC(GPP_B10, NONE),

	PAD_CFG_NF(GPP_B11, NONE, RSMRST, NF1),

	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF4),

	PAD_NC(GPP_B15, NONE),

	PAD_CFG_NF(GPP_B16, NONE, DEEP, NF2),

	PAD_CFG_NF(GPP_B17, NONE, DEEP, NF2),

	PAD_CFG_GPO(GPP_B18, 0, DEEP),

	PAD_NC(GPP_B19, NONE),

	PAD_NC(GPP_B20, NONE),

	PAD_NC(GPP_B21, NONE),

	PAD_NC(GPP_B22, NONE),

	PAD_CFG_GPO(GPP_B23, 0, DEEP),

	PAD_CFG_NF(GPP_B24, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_B25, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_T ------- */

	PAD_NC(GPP_T0, NONE),

	PAD_NC(GPP_T1, NONE),

	PAD_CFG_NF(GPP_T2, DN_20K, DEEP, NF2),

	PAD_CFG_NF(GPP_T3, DN_20K, DEEP, NF2),

	PAD_NC(GPP_T4, NONE),

	PAD_NC(GPP_T5, NONE),

	PAD_NC(GPP_T6, NONE),

	PAD_NC(GPP_T7, NONE),

	PAD_NC(GPP_T8, NONE),

	PAD_NC(GPP_T9, NONE),

	PAD_NC(GPP_T10, NONE),

	PAD_NC(GPP_T11, NONE),

	PAD_NC(GPP_T12, NONE),

	PAD_NC(GPP_T13, NONE),

	PAD_NC(GPP_T14, NONE),

	PAD_NC(GPP_T15, NONE),

	/* ------- GPIO Group GPP_A ------- */

	PAD_CFG_NF(GPP_A0, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A1, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A2, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A3, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A4, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A5, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A6, UP_20K, DEEP, NF1),

	PAD_NC(GPP_A7, NONE),

	PAD_NC(GPP_A8, NONE),

	PAD_CFG_NF(GPP_A9, DN_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_A10, NONE, DEEP, NF1),

	PAD_NC(GPP_A11, NONE),

	PAD_NC(GPP_A12, NONE),

	PAD_NC(GPP_A13, NONE),

	PAD_CFG_NF(GPP_A14, NONE, DEEP, NF2),

	PAD_CFG_NF(GPP_A15, NONE, DEEP, NF2),

	PAD_CFG_NF(GPP_A16, NONE, DEEP, NF1),

	PAD_NC(GPP_A17, NONE),

	PAD_NC(GPP_A18, NONE),

	PAD_NC(GPP_A19, NONE),

	PAD_NC(GPP_A20, NONE),

	PAD_NC(GPP_A21, NONE),

	PAD_NC(GPP_A22, NONE),

	PAD_CFG_NF(GPP_A23, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_ESPI_CLK_LOOPBK, NONE, DEEP, NF1),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_S ------- */

	PAD_NC(GPP_S0, NONE),

	PAD_NC(GPP_S1, NONE),

	PAD_NC(GPP_S2, NONE),

	PAD_NC(GPP_S3, NONE),

	PAD_NC(GPP_S4, NONE),

	PAD_NC(GPP_S5, NONE),

	PAD_NC(GPP_S6, NONE),

	PAD_NC(GPP_S7, NONE),

	/* ------- GPIO Group GPP_H ------- */

	PAD_CFG_GPO(GPP_H0, 1, RSMRST),

	PAD_CFG_GPO(GPP_H1, 1, RSMRST),

	PAD_CFG_GPO(GPP_H2, 1, RSMRST),

	PAD_NC(GPP_H3, NONE),

	PAD_CFG_NF(GPP_H4, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_H5, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_H6, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_H7, NONE, DEEP, NF1),

	PAD_NC(GPP_H8, NONE),

	PAD_NC(GPP_H9, NONE),

	PAD_NC(GPP_H10, NONE),

	PAD_NC(GPP_H11, NONE),

	PAD_NC(GPP_H12, NONE),

	PAD_NC(GPP_H13, NONE),

	PAD_NC(GPP_H14, NONE),

	PAD_NC(GPP_H15, NONE),

	PAD_NC(GPP_H16, NONE),

	PAD_CFG_GPO(GPP_H17, 0, DEEP),

	PAD_CFG_NF(GPP_H18, NONE, DEEP, NF1),

	PAD_NC(GPP_H19, NONE),

	PAD_NC(GPP_H20, NONE),

	PAD_NC(GPP_H21, NONE),

	PAD_NC(GPP_H22, NONE),

	PAD_NC(GPP_H23, NONE),

	/* ------- GPIO Group GPP_D ------- */

	PAD_CFG_GPO(GPP_D0, 0, RSMRST),

	PAD_CFG_GPO(GPP_D1, 0, RSMRST),

	PAD_CFG_GPO(GPP_D2, 0, RSMRST),

	PAD_CFG_GPO(GPP_D3, 0, RSMRST),

	PAD_NC(GPP_D4, NONE),

	PAD_NC(GPP_D5, NONE),

	PAD_CFG_NF(GPP_D6, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_D7, NONE, DEEP, NF1),

	PAD_NC(GPP_D8, NONE),

	PAD_CFG_NF(GPP_D9, NATIVE, DEEP, NF2),

	PAD_CFG_NF(GPP_D10, NATIVE, DEEP, NF2),

	PAD_CFG_NF(GPP_D11, NATIVE, DEEP, NF2),

	PAD_CFG_NF(GPP_D12, NATIVE, DEEP, NF2),

	PAD_CFG_GPO(GPP_D13, 1, PLTRST),

	PAD_CFG_GPO(GPP_D14, 1, PLTRST),

	PAD_NC(GPP_D15, NONE),

	PAD_CFG_GPO(GPP_D16, 0, PLTRST),

	PAD_CFG_TERM_GPO(GPP_D17, 1, UP_20K, RSMRST),

	PAD_CFG_TERM_GPO(GPP_D18, 0, UP_20K, RSMRST),

	PAD_NC(GPP_D19, NONE),

	PAD_CFG_NF(GPP_GSPI2_CLK_LOOPBK, NONE, DEEP, NF1),

	/* ------- GPIO Group RESERVED ------- */

	PAD_NC(GPP_CPU_RSVD_1, NONE),

	PAD_NC(GPP_CPU_RSVD_2, NONE),

	PAD_NC(GPP_CPU_RSVD_3, NONE),

	PAD_NC(GPP_CPU_RSVD_4, NONE),

	PAD_NC(GPP_CPU_RSVD_5, NONE),

	PAD_NC(GPP_CPU_RSVD_6, NONE),

	PAD_NC(GPP_CPU_RSVD_7, NONE),

	PAD_NC(GPP_CPU_RSVD_8, NONE),

	PAD_NC(GPP_CPU_RSVD_9, NONE),

	PAD_NC(GPP_CPU_RSVD_10, NONE),

	PAD_NC(GPP_CPU_RSVD_11, NONE),

	PAD_NC(GPP_CPU_RSVD_12, NONE),

	PAD_NC(GPP_CPU_RSVD_13, NONE),

	PAD_NC(GPP_CPU_RSVD_14, NONE),

	PAD_NC(GPP_CPU_RSVD_15, NONE),

	PAD_NC(GPP_CPU_RSVD_16, NONE),

	PAD_NC(GPP_CPU_RSVD_17, NONE),

	PAD_NC(GPP_CPU_RSVD_18, NONE),

	PAD_NC(GPP_CPU_RSVD_19, NONE),

	PAD_NC(GPP_CPU_RSVD_20, NONE),

	PAD_CFG_NF(GPP_CPU_RSVD_21, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_CPU_RSVD_22, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_CPU_RSVD_23, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_CPU_RSVD_24, NONE, DEEP, NF1),

	/* ------- GPIO Group vGPIO ------- */

	PAD_CFG_GPO(GPP_VGPIO_0, 0, DEEP),

	PAD_CFG_GPI_TRIG_OWN(GPP_VGPIO_4, NONE, DEEP, OFF, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_VGPIO_5, 1, NONE, DEEP, LEVEL, ACPI),

	PAD_CFG_NF(GPP_VGPIO_6, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_7, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_8, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_9, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_10, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_11, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_12, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_13, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_18, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_19, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_20, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_21, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_22, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_23, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_24, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_25, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_30, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_31, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_32, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_33, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_34, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_35, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_36, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_VGPIO_37, NONE, DEEP, NF1),

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPP_GPD ------- */

	PAD_CFG_NF(GPD0, UP_20K, PWROK, NF1),

	PAD_CFG_NF(GPD1, NATIVE, PWROK, NF1),

	PAD_CFG_NF(GPD2, NATIVE, PWROK, NF1),

	PAD_CFG_NF(GPD3, UP_20K, PWROK, NF1),

	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD6, NONE, PWROK, NF1),

	PAD_CFG_GPO(GPD7, 0, PWROK),

	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD9, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD10, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD11, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD_INPUT3VSEL, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD_SLP_LANB, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD_SLP_SUSB, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD_WAKEB, NONE, PWROK, NF1),

	PAD_CFG_NF(GPD_DRAM_RESETB, NONE, PWROK, NF1),

	/* ------- GPIO Group PCIe vGPIO ------- */

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_25, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_26, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_27, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_28, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_29, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_30, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_31, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_32, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_33, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_34, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_35, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_36, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_37, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_38, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_39, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_0, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_1, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_2, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_3, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_4, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_5, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_6, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_7, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_8, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_9, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_10, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_11, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_12, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_13, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_14, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_15, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_16, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_17, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_18, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_19, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_20, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_21, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_22, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_23, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_24, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_25, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_26, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_27, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_28, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_29, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_30, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_31, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_32, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_33, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_34, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_35, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_36, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_37, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_38, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_39, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_40, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_41, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_42, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_43, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_44, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_45, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_46, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_47, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_48, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_49, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_50, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_51, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_52, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_53, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_54, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_55, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_56, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_57, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_58, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_59, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_60, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_61, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_62, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_63, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_64, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_65, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_66, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_67, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_68, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_69, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_70, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_71, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_72, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_73, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_74, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_75, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_76, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_77, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_78, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_79, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_40, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_41, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_42, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_43, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_44, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_45, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_46, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_CPU_RSVD_47, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_80, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_81, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_82, 0, NONE, RSMRST, LEVEL, ACPI),

	PAD_CFG_GPIO_BIDIRECT(GPP_vGPIO_PCIE_83, 0, NONE, RSMRST, LEVEL, ACPI),

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group GPP_C ------- */

	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),

	PAD_CFG_GPO(GPP_C2, 0, DEEP),

	PAD_CFG_NF(GPP_C3, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_C4, NONE, DEEP, NF1),

	PAD_CFG_GPO(GPP_C5, 0, DEEP),

	PAD_CFG_NF(GPP_C6, NONE, RSMRST, NF1),

	PAD_CFG_NF(GPP_C7, NONE, RSMRST, NF1),

	PAD_NC(GPP_C8, NONE),

	PAD_NC(GPP_C9, NONE),

	PAD_NC(GPP_C10, NONE),

	PAD_NC(GPP_C11, NONE),

	PAD_NC(GPP_C12, NONE),

	PAD_NC(GPP_C13, NONE),

	PAD_NC(GPP_C14, NONE),

	PAD_NC(GPP_C15, NONE),

	PAD_NC(GPP_C16, NONE),

	PAD_NC(GPP_C17, NONE),

	PAD_NC(GPP_C18, NONE),

	PAD_NC(GPP_C19, NONE),

	PAD_NC(GPP_C20, NONE),

	PAD_NC(GPP_C21, NONE),

	PAD_NC(GPP_C22, NONE),

	PAD_NC(GPP_C23, NONE),

	/* ------- GPIO Group GPP_F ------- */

	PAD_CFG_NF(GPP_F0, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_F1, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_F2, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_F3, UP_20K, DEEP, NF1),

	PAD_CFG_NF(GPP_F4, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_F5, NONE, DEEP, NF2),

	PAD_NC(GPP_F6, NONE),

	PAD_CFG_GPO(GPP_F7, 0, DEEP),

	PAD_NC(GPP_F8, NONE),

	PAD_CFG_NF(GPP_F9, NONE, DEEP, NF1),

	PAD_CFG_GPO(GPP_F10, 0, DEEP),

	PAD_CFG_NF(GPP_F11, NONE, DEEP, NF4),

	PAD_CFG_NF(GPP_F12, NONE, DEEP, NF4),

	PAD_CFG_NF(GPP_F13, NONE, DEEP, NF4),

	PAD_NC(GPP_F14, NONE),

	PAD_NC(GPP_F15, NONE),

	PAD_CFG_NF(GPP_F16, NONE, DEEP, NF4),

	PAD_NC(GPP_F17, NONE),

	PAD_NC(GPP_F18, NONE),

	PAD_NC(GPP_F19, NONE),

	PAD_CFG_NF(GPP_F20, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_F21, NONE, DEEP, NF1),

	PAD_NC(GPP_F22, NONE),

	PAD_NC(GPP_F23, NONE),

	PAD_CFG_NF(GPP_F_CLK_LOOPBK, NONE, DEEP, NF4),

	/* ------- GPIO Group GPP_HVCMOS ------- */

	PAD_CFG_NF(GPP_L_BKLTEN, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_L_BKLTCTL, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_L_VDDEN, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_SYS_PWROK, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_SYS_RESETB, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_MLK_RSTB, NONE, DEEP, NF1),

	/* ------- GPIO Group GPP_E ------- */

	PAD_NC(GPP_E0, NONE),

	PAD_NC(GPP_E1, NONE),

	PAD_NC(GPP_E2, NONE),

	PAD_NC(GPP_E3, NONE),

	PAD_NC(GPP_E4, NONE),

	PAD_CFG_GPO(GPP_E5, 0, RSMRST),

	PAD_CFG_GPO(GPP_E6, 0, DEEP),

	PAD_NC(GPP_E7, NONE),

	PAD_NC(GPP_E8, NONE),

	PAD_CFG_NF(GPP_E9, NONE, DEEP, NF1),

	PAD_NC(GPP_E10, NONE),

	PAD_NC(GPP_E11, NONE),

	PAD_NC(GPP_E12, NONE),

	PAD_NC(GPP_E13, NONE),

	PAD_NC(GPP_E14, NONE),

	PAD_CFG_NF(GPP_E15, NONE, DEEP, NF2),

	PAD_CFG_NF(GPP_E16, NONE, DEEP, NF2),

	PAD_NC(GPP_E17, NONE),

	PAD_CFG_NF(GPP_E18, NATIVE, DEEP, NF4),

	PAD_CFG_NF(GPP_E19, NATIVE, DEEP, NF4),

	PAD_CFG_NF(GPP_E20, NATIVE, DEEP, NF4),

	PAD_CFG_NF(GPP_E21, NATIVE, DEEP, NF4),

	PAD_CFG_NF(GPP_E22, DN_20K, DEEP, NF2),

	PAD_CFG_GPO(GPP_E23, 1, PLTRST),

	PAD_NC(GPP_E_CLK_LOOPBK, NONE),

	/* ------- GPIO Community 5 ------- */

	/* ------- GPIO Group GPP_R ------- */

	PAD_CFG_NF(GPP_R0, NONE, DEEP, NF1),

	PAD_CFG_NF(GPP_R1, NATIVE, DEEP, NF1),

	PAD_CFG_NF(GPP_R2, NATIVE, DEEP, NF1),

	PAD_CFG_NF(GPP_R3, NATIVE, DEEP, NF1),

	PAD_CFG_NF(GPP_R4, NONE, DEEP, NF1),

	PAD_NC(GPP_R5, NONE),

	PAD_NC(GPP_R6, NONE),

	PAD_NC(GPP_R7, NONE),
};

#endif /* MAINBOARD_ERYING_SRMJ4_GPIO_H */
